# ~/.config/yazi/keymap.toml (or %APPDATA%\yazi\keymap.toml)

[manager]
e = "open"      # Changed to use Yazi's 'open' action
o = "open"      # Add 'o' to also use Yazi's 'open' action
enter = "open"  # Changed to use Yazi's 'open' action

# Your existing navigation keymap:
prepend_keymap = [
  { on = "h", run = "leave", desc = "Go to parent directory" },
  { on = "j", run = "arrow 1", desc = "Move down" },
  { on = "k", run = "arrow -1", desc = "Move up" },
  { on = "l", run = "enter", desc = "Enter directory or open file" },
]